exclude: '\.(sql|SQL)$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: ['--unsafe']
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=120000"]
      - id: check-json
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        types: [python]
        args: [--fix]
        language: system
      - id: ruff-format
        name: ruff-format
        types: [python]
        entry: poetry run ruff format
        language: system
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
